### ISSUE TITLE
使用app添加节点失败

### ISSUE THREAD

**Issue by bigtan** [chanify/chanify#1]
`./chanify serve --endpoint https://xxx.xxx.cn --host 127.0.0.1 --port 8080 --name xxx --secret xxxxx`

然后用的caddy把`https://xxx.xxx.cn`反代到公网上，扫描二维码，无法添加节点

**Comment by bigtan** [comment]
我自己试着调试了一下，是viper没有正确的读到命令行：
https://github.com/chanify/chanify/blob/main/cmd/serve.go#L82

**Comment by wizjin** [comment]
十分感谢你的PR，这个是我的失误。

**Comment by bigtan** [comment]
这个修好以后，成功添加了节点，还是没法使用自定义的节点。

**Comment by bigtan** [comment]
post的用法修改了，跟文档的用法不一样，难怪。

**Comment by wizjin** [comment]
不好意思啊！这两天正好在重构，有些思路我还在调整中，服务器端还没最终定稿，接口目前还没有稳定。
一切顺利的话这个月底会正式发布1.0.0版本稳定接口，之后的版本会对api做向下兼容，有建议欢迎随时提。

**Comment by bigtan** [comment]
我看了一下代码  消息的推送最后还是要集中到api.chanify.net进行推送  既然自建服务器了为什么还要把推送集中到一台服务器呢。

加个telegram吧，方便聊 t.me/bigtan

**Comment by wizjin** [comment]
按照我目前的设计，这个Node server会有两种工作模式：
1. serverless模式，这个是目前代码已经完成的。Node server无状态不保存任何数据，所以客户端apns的token保存在api.chanify.net。Node server加密发送消息，所以即使集中到一台服务器也能保证数据安全。
2. serverful模式，这个需要有数据库用于保存客户端apns的token，然后由node server直接发送数据。目前还在开发中，计划1.0.0版本中完整包含这个模式。

**Comment by bigtan** [comment]
期待1.0，市面上找了好多推送软件都没有能够解决我的需求的，目前来看chanify算是最接近的了。

**Comment by wizjin** [comment]
v1.0.0已发布，已经支持自建服务器直接推送消息。

- 需要iOS版本1.0.0以上
- Node节点需要删除重新添加
- 需要使用重新生成的Token
- 统一了自建服务器和默认服务的发送API接口

具体请参看README

**Comment by bigtan** [comment]
ubuntu@VM-12-12-ubuntu:~$ /usr/local/bin/chanify serve --endpoint https://bark.estan.cn --host 127.0.0.1 --port 8080 --name Estan --datapath=~/.chanify
2021/03/20 23:36:18 Launching service...
2021/03/20 23:36:18 Init service failed: In serverless mode, secret is required

**Comment by wizjin** [comment]
看一下/.chanify文件夹是否存在，权限是否可写入，程序不会自动创建文件夹。

**Comment by bigtan** [comment]
--datapath=/data 就行了  确实是这个问题

**Comment by bigtan** [comment]
等iOS的1.0推送吧，我用0.9都是提示invalid token

**Comment by wizjin** [comment]
Token的校验逻辑变了，现在通过node的Token，node都会校验。
原来serverless的时候是由api.chanify.net校验的。

PS：iOS1.0的版本苹果已经在审核了，估计明后天应该就能推送了吧！
