### ISSUE TITLE
发送图片消息中的文件路径是如何设定的，是URL还是文件地址？

### ISSUE THREAD

**Issue by aston314** [chanify/chanify#101]
$ curl --form "image=@<jpeg 文件路径>" "http://<address>:<port>/v1/sender/<token>"

**Comment by wizjin** [comment]
你好，发送图片里面是填写本地图片文件路径的。

**Comment by aston314** [comment]
我用NAS,这个路径该怎么填写，我看到Chrome插件发送图片不用选择本地图片文件路径。

**Comment by wizjin** [comment]
chrome 是因为插件处理了相关问题，如果在浏览器里面可以看到图片可以直接用chrome 插件发送。NAS 的话看你打算怎么发送了，如果是用 windows 的共享访问可以试一下 chanify-win 插件；如果是在 NAS 上用命令行的话需要你知道文件路径。

命令行可以尝试先用 pwd 获取当前目录完整路径，然后再手动加上图片路径。

**Comment by aston314** [comment]
请问是作了哪些相关处理呢，我现在上传图片，在Chanify中都显示为文件了，不能实时预览，要点击才能看。

**Comment by aston314** [comment]
已经解决了，谢谢。
现在可以通过使用url来发送图片了。
不需要本地路径。

**Comment by wizjin** [comment]
不客气

**Comment by wizjin** [comment]
> 请问是作了哪些相关处理呢，我现在上传图片，在Chanify中都显示为文件了，不能实时预览，要点击才能看。

chrome 插件会先直接读取图片数据，然后再使用 http 的 multipart/form-data 模式发送图片消息。
