### ISSUE TITLE
作为无状态服务启动的时候的参数问题

### ISSUE THREAD

**Issue by liudaolunboluo** [chanify/chanify#12]
参数--secret=<secret key> 的key从哪里可以获取；--endpoint=http://<address>:<port> 这个ip和端口就是本地的吗，要和前面的ip端口一致吗？

**Comment by wizjin** [comment]
1. ```key```可以自己取一个随机内容，这个key是用来生成服务器密钥的，只要保证key一样，服务器就会被认为是同一个，一旦key丢失了就要重新在iOS添加服务器。所以请保护好自己的key，不要泄漏，不要告诉别人，通讯安全全靠这个key了。可以使用下面的命令来随机生成一个：

```bash
openssl rand -base64 32
```

2. --endpoint=http://这个ip和端口是用来给iOS连接服务器的，可以和前面的ip端口一致，也可以不一样。具体看你的网络环境决定的。确保在手机上可以打开endpoint的那个网址就OK

**Comment by liudaolunboluo** [comment]
意思是--endpoint 这个IP端口必须启动一个服务吗？还是我本机启动的chanify服务就可以了

**Comment by wizjin** [comment]
你在本机启动，并且iOS和你机器在一个内网的话，就填你自己机器的ip地址就可以。
这个配置是给想在公网使用，并且前面挡了一层Nginx之类的反向代理的时候使用的。

**Comment by liudaolunboluo** [comment]
哦哦所以端口不是必填的，只要我的终端能访问得到这个ip也可以

**Comment by wizjin** [comment]
是的，看你的网络拓扑

```
手机 --A--> Nginx --B--> Chanify

有代理的模式，A就是看endpoint参数，B就是前面的host和port
```

```
手机 --A-->  Chanify

直连模式，host、port和endpoint都是一样的。
```

例如我自己的机器IP是192.168.0.100，可以直接这样，endpoint直接省略也可以。

```bash
chanify serve --host=192.168.0.100 --port=8080 --secret=<secret key> --name=<node name>
```

然后用```http://192.168.0.100:8080```获取的二维码添加就可以了。

**Comment by liudaolunboluo** [comment]
如果添加了ngnix的话，那endpoint就是nginx反向代理出来的域名吗还是nginx的IP和端口

**Comment by wizjin** [comment]
如果加了nginx的话，endpoint就是反向代理出来的域名和端口，不是nginx的IP和端口。

**Comment by liudaolunboluo** [comment]
如果ng默认就是80端口的话反向代理出来的域名是http://liudaolunhuiboluo.test.com/chanify/的话，是否endpoint参数就是：--endpoint=http://liudaolunhuiboluo.test.com/chanify/ 然后保证http://liudaolunhuiboluo.test.com/chanify/用终端设备可以访问就可以了

**Comment by wizjin** [comment]
对的，是这样的。

**Comment by liudaolunboluo** [comment]
但是手机APP扫描二维码的时候报错链接节点服务器失败，我手机开4G明明可以打开这个二维码的网站啊

**Comment by wizjin** [comment]
看一下这个```http://liudaolunhuiboluo.test.com/chanify/rest/v1/info```有内容返回吗？APP靠这个接口添加节点的。

**Comment by liudaolunboluo** [comment]
{"nodeid":"AEPUKBKYUPHE4TA5ZI2BAQP2KYPXRTEOFM","name":"zyfTest","version":"1.0.2","pubkey":"BD3GwHBNJzcsbALdPqT8HT0NB4tOdJq4vQztuc9tMQo05iflqdutFI1Z/IqoF5EPBZLhu8y9e5Gnmg9lh24Sef4","endpoint":"http://test-usercenter.sinoiov.com/chanify","features":["msg.text"]}   有的呢

**Comment by wizjin** [comment]
@liudaolunboluo 看了一下应该是APP对于HTTP请求兼容的有Bug，我今晚iOS会提交苹果审核1.0.3会修复这个问题。给你造成麻烦了，不好意思。

如果只是发送文本的话，你可以先用内网添加好后也可以用，添加完后APP不会再访问服务器了，不影响使用。回头1.0.3升级完只要重新添加更新一下就ok了。

**Comment by liudaolunboluo** [comment]
您太客气了，我用内网添加试试

**Comment by wizjin** [comment]
@liudaolunboluo 手机APP的1.0.3已经过审了，晚点有空可以更新一下，然后麻烦试一下公网的添加是不是可以。谢谢啦！
