### ISSUE TITLE
bug: Special characters give "invalid content" message

### ISSUE THREAD

**Issue by bernzrdo** [chanify/chanify#126]
**Describe the bug**
When I try to use characters like `á`, `õ`, `—`, Chanify responds with `{ res: 400, msg: 'invalid content' }`

**To Reproduce**
1. Create a POST request to `api.chanify.net` with a special character (`á`, `õ`, `—`) in it's content
2. See error

**Expected behavior**
I should recieve a notification with those characters

**iOS info**
 - Device: iPhone 12
 - OS: iOS 15.5
 - Version: 1.3.11

**Comment by wizjin** [comment]
I need more information:

- How to post request? (program or tools)
- POST request `Content-Type`
- POST body

If Content-Type is `appliaction/json, send success.
If Content-Type is `application/x-www-form-urlencoded`, please urlencoded characters.

Thank you very much.

**Comment by bernzrdo** [comment]
Thank you for the quick reply.

I am using `application/json`. Here's a snippet of the code I am using:

```js
const data = JSON.stringify({
    title: 'nova mensagem',
    text: msg,
    actions: [`responder|twitter://post?message=${msg} - bernzrdo.wtf`],
    sound: 1
})

const notifReq = https.request({
    hostname: 'api.chanify.net',
    port: 443,
    path: '/v1/sender/' + process.env.CHANIFY_TOKEN,
    method: 'POST',
    headers: {
        'Content-Type': 'application/json; charset=utf-8',
        'Content-Length': data.length
    }
}, notifRes=>{
    var data = '';
    notifRes.on('data', c=>data += c);
    notifRes.on('end', ()=>{
        data = JSON.parse(data);
        if(!('request-uid' in data)) console.log(data);
        res.render('twitter-result', { success: 'request-uid' in data });
    });
});
notifReq.write(data);
notifReq.end();
```

**Comment by wizjin** [comment]
@bernzrdo `JSON.stringify` return non-UTF-8 string.

Please change from

```javascript
const data = JSON.stringify({
    title: 'nova mensagem',
    text: msg,
    actions: [`responder|twitter://post?message=${msg} - bernzrdo.wtf`],
    sound: 1
})
```

to

```javascript
const data = new TextEncoder("utf-8").encode(JSON.stringify({
    title: 'nova mensagem',
    text: msg,
    actions: [`responder|twitter://post?message=${msg} - bernzrdo.wtf`],
    sound: 1
}))
```

Thanks.

**Comment by bernzrdo** [comment]
It worked! Thank you very much! :)
