### ISSUE TITLE
bug: iOS15.2,XR mobile Flashback

### ISSUE THREAD

**Issue by BigLight-H** [chanify/chanify#127]
The latest version of the app crashes in ios 15.2

**Comment by wizjin** [comment]
I will check and fix this bug.

Thanks.

**Comment by wizjin** [comment]
Sorry, I use a new API in Chanify 1.3.11.

This crash will be fixed in [1.3.12](https://github.com/chanify/chanify-ios/releases/tag/1.3.12).

Thanks.
