### ISSUE TITLE
bug: SSL 证书过期

### ISSUE THREAD

**Issue by dluffymonkey** [chanify/chanify#129]
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by xd1gital** [comment]
Yes api.chanify.net SSL certificate has expired
````
*   Trying 104.200.25.4:443...
* TCP_NODELAY set
* Connected to api.chanify.net (104.200.25.4) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, certificate expired (557):
* SSL certificate problem: certificate has expired
* Closing connection 0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html
````
![api_chanify_net_cert](https://user-images.githubusercontent.com/31955226/179205286-225780b5-734f-4bd2-8c03-f1b1a3b56d95.jpg)
