### ISSUE TITLE
自建服务器的问题定位

### ISSUE THREAD

**Issue by LitSummer** [chanify/chanify#13]
你好，我现在控制台能收到get和post发送的数据，但是手机一直没收到，用api.chanify.net的是可以秒收到的，现在该怎么定位中间的问题呢？谢谢。另外endpoint域名和ip都试过，防火墙已关，分别在两台机器上实验过，是不是随便一台机器都可以往苹果的服务器发请求？

**Comment by wizjin** [comment]
可以看一下服务器输出的日志。
1. 先确定是不是添加手机成功了，如果有```Bind user: <用户ID>````的日志就是添加成功了，不然就是没成功。
2. 天加没成功可以在手机上用safari开一下endpoint的域名，看一下是不是能打开网页。
3. 如果添加成功了，可以看一下发送消息的日志是什么。

**Comment by LitSummer** [comment]
谢谢，我试了一下，bind user成功，有日志，endpoint能输出favicon，就那张节点的图，postman发送消息后，显示
`2021/03/29 15:35:28 200 |  12x.xx.x.x | GET /v1/sender/CID_3oYGEiJBQk00NlNRR0JXTFdZR0VaRzNNVExxxxxxxxx 30.149627ms "PostmanRuntime/7.26.10"`，只有这一条日志，这是正常的么？ @wizjin

**Comment by wizjin** [comment]
看日志是发送成功了，能问下日志里面的```serverless```是true还是false。
还有自建的服务器用的Token和用api.chanify.net的Token是2个，不要搞混了。

**Comment by LitSummer** [comment]
serverless是false，token是选的自己节点的token，apichanify的token试过是没问题的 @wizjin

**Comment by wizjin** [comment]
晚上我用postman试一下。能访问```https://api.push.apple.com```的话都能收到。
杀掉APP再打开应该能看到如下的日志

```
2021/03/29 16:28:42 200 |  12x.xx.x.x | POST /rest/v1/push-token
```

如果没看到就是注册token失败了。

**Comment by LitSummer** [comment]
参考[https://github.com/chanify/chanify/issues/12](url)，我也是用的http，可能就是这个问题

**Comment by wizjin** [comment]
@LitSummer 好的，手机1.0.3已经发布了，回头可以升级试一下。如果OK的话麻烦告知一下，到时候这个issues我就关了。谢谢啦！

**Comment by wizjin** [comment]
duplicate #12
