### ISSUE TITLE
bug:  Macos not receiving msg

### ISSUE THREAD

**Issue by daveteu** [chanify/chanify#130]
**issue 1**
Login with QR code with macos app (downloaded today)

Send message to any channels using curl

```
curl --form-string "text=hello" https://api.chanify.net/v1/sender/code
```

Only IOS receive the message, macos didn't.

-----

**Issue 2**
1) Create channel in IOS
2) Login with QR code in MacOS

New channel is not shown in macos

**Comment by wizjin** [comment]
No information will be saved in chanify server.
issue 1:
Please add channel in iOS & MacOS

Issue 2:
Chanify can not sync any information.

**Comment by daveteu** [comment]
When I add the same channel (same code) in macos and ios, their code is different
Macos
```
CIC37JoGEiJBQ0xRUUNTSEVJSkZKMjZCVzNHSFhOWExNMjdPMllTQTI0IggIAhoEZGF2ZSoiQUYyUUMzUE5IWVhSU01JNzZFTTVRSDM2SFQzWVg0NDZMSQ..LyZgocyA5qvS9258K5IvzCxXqjz5EzFeWtG32vJLDnQ
```

ios

```
CIC37JoGEiJBQ0xRUUNTSEVJSkZKMjZCVzNHSFhOWExNMjdPMllTQTI0IggIAhoEZGF2ZSoiQUYyUUMzUE5IWVhSU01JNzZFTTVRSDM2SFQzWVg0NDZMSQ.iOzO1ZcRKBUOsGFHJzZIQb8XE_58mAZCLZ94qAaFj9c.LyZgocyA5qvS9258K5IvzCxXqjz5EzFeWtG32vJLDnQ
```

It's missing the middle bit and server returns no device found
