### ISSUE TITLE
python 发送带标题的告警

### ISSUE THREAD

**Issue by sswking** [chanify/chanify#139]
如何发送通过python发送 带标题的
parse.urlencode({  "token": "<令牌Token>",
                          "title": "<消息标题>",
                          "text": "<文本消息内容>"}).encode()
使用上面格式，也只得到text内容。感谢指点

**Comment by wizjin** [comment]
你好，请问完整的代码是什么样的，只有这些看不出什么问题。

**Comment by sswking** [comment]
biaoti = "baiti"
neirong = "context"

url = "https://xxxx/v1/sender/CICSuaQGEiJBRFczMzVITUJET1VZR1NXNkRYM0xDQUhTSFZaUUVaQlpNIgkIAhoFY2VzaGkqIkFFWDdGRkdITk1VUTdDNU1ZMjRFQ1hXWUtUNUY0WDZZTkE.rZ3z3OXsLFzm7DiolKxa4rEeNs76d5CCEOAaix_GKUg.BAreLsALr6qlsbDdXvboQ4PotqQnOzixjs6qHtX7zAs" + "?"

data = {
    "text": neirong,
    "title": biaoti
}
response = requests.post(url,data=data)
print(response.text)

==================
感谢

**Comment by wizjin** [comment]
```python
biaoti = "baiti"
neirong = "context"

url = "https://xxxx/v1/sender/CICSuaQGEiJBRFczMzVITUJET1VZR1NXNkRYM0xDQUhTSFZaUUVaQlpNIgkIAhoFY2VzaGkqIkFFWDdGRkdITk1VUTdDNU1ZMjRFQ1hXWUtUNUY0WDZZTkE.rZ3z3OXsLFzm7DiolKxa4rEeNs76d5CCEOAaix_GKUg.BAreLsALr6qlsbDdXvboQ4PotqQnOzixjs6qHtX7zAs"

data = {
"text": neirong,
"title": biaoti
}
response = requests.post(url,json=data)
print(response.text)
```
用`json`试一下，url后面不需要`?`

**Comment by sswking** [comment]
使用json可以成功了，感谢大佬
