### ISSUE TITLE
无状态服务器发送消息返回401

### ISSUE THREAD

**Issue by liudaolunboluo** [chanify/chanify#14]
浏览器访问http://ip:port/v1/sender/<token>?text=hellp返回{"msg":"invalid token","res":401}   换成postman访问之后仍然返回{"msg":"invalid token","res":401}

**Comment by LitSummer** [comment]
你的token不对，你去app里，频道右滑，点进去了的token才是需要的token，不是你设置中的用户或者设备那两栏

**Comment by wizjin** [comment]
@liudaolunboluo 需要token才能访问，
```
http://ip:port/v1/sender/?text=hellp&token=<你的token>
```
