### ISSUE TITLE
feat: 可否增加对 Vercel Storage 的支持

### ISSUE THREAD

**Issue by yb** [chanify/chanify#144]
Hi @wizjin,

首先很感谢开发了 Chanify，我使用它两年多，一直非常稳定，几乎满足了所有需求。

目前在独立部署 Chanify 的时候，需要一个 MySQL 或 SQLite 数据库，因此我无法将它部署在常规的 serverless 服务上。我认为通知推送是一个对在线率要求非常高的基础服务，于是单独使用一个 VPS 部署它（性能非常低，但独立不受其它服务影响）。

最近我发现知名的 serverless 服务商 Vercel 已推出几种数据库，可以持久化存储数据，其中也包括结构化数据的 Vercel Postgres，于是有了将 Chanify 部署到 Vercel 上的想法。

但我确实没写过 go，因此想问一下，是否可以增加对 Vercel Storage 的支持？

非常感谢

reference: https://vercel.com/docs/storage

**Comment by wizjin** [comment]
Chanify部署成有状态的时候不光要有数据库，还要存储文件。

**Comment by yb** [comment]
@wizjin 确实，我忽视了这点，我一直没有推送过附件。感谢。
