### ISSUE TITLE
发送消息支持markdown语法这种带链接的吗？

### ISSUE THREAD

**Issue by liudaolunboluo** [chanify/chanify#15]
比如说想直接点击消息就跳转，还有后面能支持带图片吗？

**Comment by wizjin** [comment]
目前暂时不支持markdown语法。

现在文本消息里面如果内容里面有连接可以直接点击跳转的。

图片发送目前支持单独发图片

```bash
curl --form-string "token=<token>" --form "image=@<本地文件路径>" "http://<ip>:<port>/v1/sender"
```
服务器要用stateful mode，你可以先试一下，1.0.2图片发送可能还有一点Bug，我还在抽空改中... ...

**Comment by wizjin** [comment]
图片已经在v1.0.4中支持了，可以试一下，有意见建议欢迎一起讨论。

**Comment by wizjin** [comment]
v1.0.5支持链接类型的通知，点击后可以直接跳转，markdown格式近期内暂时没有支持的计划。
