### ISSUE TITLE
链接类型优化

### ISSUE THREAD

**Issue by axelburks** [chanify/chanify#28]
1.支持通过 Safari 或 SVC 打开链接
2.支持打开 url scheme 类型的链接
3.点击通知消息可以直接打开链接

支持通过 Safari 打开也就自动支持了 url scheme，而且也不再需要自行实现 webview

**Comment by wizjin** [comment]
1. iOS下个版本会在长按的菜单中会增加用Safari打开
2. 参见 #30 
3. 参见 #31 

谢谢意见
