### ISSUE TITLE
怎么用nginx反代啊?

### ISSUE THREAD

**Issue by Jonnyan404** [chanify/chanify#36]
求解!谢谢

这么启动的 
 `chanify serve --host=0.0.0.0 --port=10000 --name=apple --datapath=/opt/chanify --endpoint=https://xxx.xxx.fun`

**Comment by wizjin** [comment]
可以这样配置：

```nginx
server {
	listen              443 ssl http2;
	server_name         xxx.xxx.fun;
    ...
	location / {
		client_max_body_size			      20M;
		client_body_buffer_size				  10M;
		proxy_set_header   Host               $host;
		proxy_set_header   X-Real-IP          $remote_addr;
		proxy_set_header   X-Forwarded-Proto  $scheme;
		proxy_set_header   X-Forwarded-For    $proxy_add_x_forwarded_for;
		proxy_pass http://<Node服务器的内网IP>:10000;
	}
    ...
}
```

PS: 如果只是自己用，放在公网上的话建议加上`--registerable=false --whitelist=<user1 id>`，防止被被人滥用。

**Comment by Jonnyan404** [comment]
@wizjin  但是我这里报 502,打不开  https://xxx.xxx.fun

**Comment by Jonnyan404** [comment]
2021/04/12 19:21:04 Node server name: apple, version: 1.0.7, serverless: false, node-id: AFLMJCR4YALN7VEVADEBEX4Q235JBOTVHU
2021/04/12 19:21:04 Launch service 0.0.0.0:10000

**Comment by wizjin** [comment]
502是Bad Gateway，应该是

 ```nginx
proxy_pass http://<Node服务器的内网IP>:10000;
```

这里Node服务器的内网IP地址不正确，试一下Nginx所在的服务器是不是可以访问到这个ip和端口。
可以用telnet或者nc来测试一下：

```bash
nc -v <ip address> 10000
```

**Comment by Jonnyan404** [comment]
我确定可以访问,因为同机器上还部署着很多其它服务.

**Comment by Jonnyan404** [comment]
A和B同一内网,,,chanify部署在A机器,通过B机器的nginx转发.

**Comment by wizjin** [comment]
我的意思是测试一下看看这个端口是不是可以访问。

**Comment by Jonnyan404** [comment]
> 我的意思是测试一下看看这个端口是不是可以访问。

我telnet过了,是通的

**Comment by Jonnyan404** [comment]
![image](https://user-images.githubusercontent.com/20352705/114388692-a0e31a80-9bc6-11eb-9b9e-ceb2e8ff83e6.png)

**Comment by Jonnyan404** [comment]
2021/04/12 19:32:44 200 |        10.0.0.6 | GET / 2.708764ms "curl/7.58.0"
2021/04/12 19:37:56 200 |        10.0.0.6 | GET / 4.707982ms "curl/7.58.0"

**Comment by Jonnyan404** [comment]
用endpoint访问就是不行

**Comment by wizjin** [comment]
ngnix上用的是`location / `还是还有其他路径，是不是和其他服务冲突了？

如果有其他路径的话配置会不一样
```nginx
server {
	listen              443 ssl http2;
	server_name         xxx.xxx.fun;
    ...
	location /chanify/ {
		client_max_body_size			      20M;
		client_body_buffer_size				  10M;
		proxy_set_header   Host               $host;
		proxy_set_header   X-Real-IP          $remote_addr;
		proxy_set_header   X-Forwarded-Proto  $scheme;
		proxy_set_header   X-Forwarded-For    $proxy_add_x_forwarded_for;
		proxy_pass http://<Node服务器的内网IP>:10000/;
	}
    ...
}
```

启动要改成这样
```bash
chanify serve --host=0.0.0.0 --port=10000 --name=apple --datapath=/opt/chanify --endpoint=https://xxx.xxx.fun/chanify
```

**Comment by Jonnyan404** [comment]
> ngnix上用的是`location / `还是还有其他路径，是不是和其他服务冲突了？
> 
> 如果有其他路径的话配置会不一样
> 
> ```nginx
> server {
> 	listen              443 ssl http2;
> 	server_name         xxx.xxx.fun;
>     ...
> 	location /chanify/ {
> 		client_max_body_size			      20M;
> 		client_body_buffer_size				  10M;
> 		proxy_set_header   Host               $host;
> 		proxy_set_header   X-Real-IP          $remote_addr;
> 		proxy_set_header   X-Forwarded-Proto  $scheme;
> 		proxy_set_header   X-Forwarded-For    $proxy_add_x_forwarded_for;
> 		proxy_pass http://<Node服务器的内网IP>:10000/;
> 	}
>     ...
> }
> ```
> 
> 启动要改成这样
> 
> ```shell
> chanify serve --host=0.0.0.0 --port=10000 --name=apple --datapath=/opt/chanify --endpoint=https://xxx.xxx.fun/chanify
> ```

按照你这个改了,一样不可以,,,还是502,我有个安卓的 gotify,也是这么反代的,没发现问题.

**Comment by Jonnyan404** [comment]
噢,sorry   可能我的锅,我在排查下

**Comment by wizjin** [comment]
nginx的错误日志有吗？我这里也是这样配置nginx反向代理，没发现有什么问题。一时之间也想不到是什么原因。endpoint只是给手机访问手机会用到的参数，不会影响node的网络状况。

**Comment by wizjin** [comment]
> 噢,sorry   可能我的锅,我在排查下

没关系，能找到问题就好。

**Comment by Jonnyan404** [comment]
> > 噢,sorry   可能我的锅,我在排查下
> 
> 没关系，能找到问题就好。

谢谢耐心解答!

**Comment by Jonnyan404** [comment]
原因找到了,是因为oracle的云服务器,本机还有个防火墙,我忘记这回事儿了.

**Comment by wizjin** [comment]
能工作就好，还有问题欢迎随时提。
