### ISSUE TITLE
Bug: 同时设置 title 和 text 参数时，通知显示两个 title 内容

### ISSUE THREAD

**Issue by axelburks** [chanify/chanify#43]
![image](https://user-images.githubusercontent.com/11376445/114712511-c442cc80-9d62-11eb-9090-2e4433405e9c.png)
![image](https://user-images.githubusercontent.com/11376445/114712538-cad14400-9d62-11eb-83dd-e32dfd252b13.png)

**Comment by wizjin** [comment]
fix in iOS App(v1.0.9)

See: https://github.com/chanify/chanify-ios/issues/6
