### ISSUE TITLE
feat: 希望可以在客户端的消息显示页面增加对a标签的支持

### ISSUE THREAD

**Issue by zr60** [chanify/chanify#58]
**功能相关性**
在使用推送文本信息时，会推送一些需要实时处理的信息。

**解决方案**
希望可以考虑在显示页面，增加对a标签的支持，这样可以对一些实时信息进行交互。

**相关考虑**
 目前使用的方案是推送两次，先推送文本信息进行提醒，然后推送一个请求处理的url，比较麻烦。

**其他**
相关界面模拟 希望作者大大可以考虑
![t1](https://user-images.githubusercontent.com/63586134/116786259-3986ff00-aad0-11eb-83b9-c176db70d24a.jpg)

**Comment by wizjin** [comment]
谢谢你的意见，暂时不打算在消息中添加html的 `a` 标签。

目前计划会在消息上支持添加多个action，每个action点击会调用对应的url，显示会显示在消息底部。

开发会安排在 macOS 支持做完之后。

**Comment by zr60** [comment]
感谢回复 是我思维惯势了
添加多个action并调用 是更好的解决方案

**Comment by wizjin** [comment]
计划 v1.1.4 版本支持，参见 #59.
