### ISSUE TITLE
go install Installation error

### ISSUE THREAD

**Issue by BigLight-H** [chanify/chanify#61]
go install: version is required when current directory is not in a module
        Try 'go install github.com/chanify/chanify@latest' to install the latest version
Is there no version number? For example: @1.0

**Comment by wizjin** [comment]
I will fix README for this bug.

Thank you very much.

**Comment by wizjin** [comment]
Workaround  for install from source  in v1.1.4 

```bash
$ git clone https://github.com/chanify/chanify.git
$ cd chanify
$ make build
$ ./chanify version
```

Install from source in v1.1.5
```bash
$ git clone https://github.com/chanify/chanify.git
$ cd chanify
$ make install
```
