### ISSUE TITLE
请问频道的令牌是有有效期的吗？

### ISSUE THREAD

**Issue by yb** [chanify/chanify#69]
在频道信息的右上角，看到盾牌的小图标，点进去有个到期时间，而且是只读的，不能修改。
请问这个是令牌的到期时间吗？那到期之后所有部署出去的令牌都得更新，才能正常发送消息？

**Comment by wizjin** [comment]
你好，

1. 令牌是有有效期的，默认是90天
2. 盾牌的小图标，点进去那个到期时间是可以修改的，修改后会刷新令牌
3. 令牌的到期后所有部署出去的令牌都得更新才能发送消息

如果你不能修改时间请告知下 iOS 版本和 Chanify 版本，我这边最新版本是可以修改的。

谢谢。

**Comment by yb** [comment]
@wizjin 

版本：iOS 14.6，Chanify 1.1.6
描述：进入盾牌小图标页面，选择新的时间，页面上没有保存之类的按钮，只有左上角的返回，返回之后再进入盾牌页面，时间依然是修改前的时间。

说回有效期的问题：

无论是在创建频道时，还是在复制令牌时，都没提示令牌有有效期一说，包括官网和 GitHub 都没提到。

如果今天我没注意到小盾牌，已经将令牌部署到服务器上（当服务器发生错误时可以通知我），90 天之后我就收不到消息了，这，不太合理吧？

建议增加长期有效令牌（但也可以手动更新），如果不行，至少也得增加续期/换新令牌的 api 吧。如果创建了几十个频道、部署到几十个不同业务中，每 90 天就要手动换新一次，那真是折腾…

**Comment by wizjin** [comment]
@yb 你好，

首先，你选择时间之后下面的令牌就已经重新生成了，在这个页面点击相应频道后面的复制，复制出来的令牌就是你选择的过期时间的令牌了。

其次，感谢你的建议，之后我会增加相关的提示信息。

最后，出于安全的考虑，整个令牌的生成过程完全在客户端完成，服务器只是验证这个令牌。所以就目前的设计并没有办法提供自动续期的 API。如果需要长期有效目前最多可自定义5年有效期的令牌。

谢谢

**Comment by yb** [comment]
@wizjin 
话说盾牌页面里的令牌，和频道信息页面的令牌，是不一样的吗？是可以同时存在的？
因为在盾牌页面生成的新令牌，回到频道信息页面，也依旧是旧的令牌，即便整个 APP 退出重新打开，频道信息页面也是旧的。

**Comment by wizjin** [comment]
@yb 

令牌是由客户端生成的，在服务器并不会保存令牌，所以可以生成多个令牌。

每个生成出来的令牌在有效期内都会一直有效，并不会因为生成新的令牌导致旧的令牌失效。

基于上面的原因，为了防止令牌泄漏后导致的安全问题，所以默认有效期只设置了90天。

**Comment by wizjin** [comment]
@yb 没错，在有效期内令牌就可用，因为令牌是绑定频道的，可见的解决方案是禁用频道，另外的方案是重新生成用户账号才可以避免。

很高心你能提出建议，但是十分抱歉，因为 Chanify 是去中心化设计的，按照目前的账号体系，长效令牌+手动换新 的话是没办法实现的。因为没有一个中心服务器作为令牌凭证的最终裁决者，这也是为什么 Chanify 能够比较方便自建服务器和 serverless 的原因。

因为 长效令牌+手动换新，是需要服务器保存短期令牌的，这样就需要服务器有自己的存储，而目前 Chanify 是可以无存储运行的，强制令牌要有存储才能工作违背了这个原则。

谢谢！

**Comment by yb** [comment]
@wizjin 目前没有禁用频道的功能吧，只有删除，删除之后历史记录还在吗？这点我不确定，如果历史记录里有重要信息，那就很蛋疼了，一边检查备份，一边被刷消息… 直到删除

**Comment by yb** [comment]
> 因为 长效令牌+手动换新，是需要服务器保存短期令牌的，这样就需要服务器有自己的存储，而目前 Chanify 是可以无存储运行的，强制令牌要有存储才能工作违背了这个原则。

我大概明白你的意思了，只要令牌符合校验，服务器就进行推送，而只要推送了，就会有信息提醒，来不及在客户端再做校验，客户端的校验 顶多是让消息不进入对应频道，但 iOS 的消息提示是苹果那边控制的，对吗？

**Comment by wizjin** [comment]
@yb 目前没有增加禁用频道的功能，后面会考虑添加。iOS 的消息提示那边是可以控制不提示的。目前就是如果令牌失效，服务器即使强制推送，在手机端也不会收到提示。

所以，目前如果是用户自己不小心泄漏了令牌还没有比较好的方案处理。

但是如果是服务器有安全隐患，只需要在 iOS 上删除服务器就可以了。之前的消息都会在，然后新消息就不会收到，也不会有提示。

所以如果是自建的服务器，令牌泄漏了有简单的解决方案：就是 iOS 删除服务器，然后重置服务器的 secret，iOS 添加新的服务器就可以了。但是问题是之前授权给这台服务相关的令牌就会全部失效，需要使用新生成的令牌才能工作。

后续我会考虑如何改善令牌泄漏的问题。

**Comment by yb** [comment]
@wizjin 好的，谢谢，期待后续更新。

**Comment by wizjin** [comment]
谢谢，还有意见欢迎随时提。

ref: https://github.com/chanify/chanify/issues/70

**Comment by wizjin** [comment]
@yb v1.1.9 支持在 iOS 添加令牌黑名单，在黑名单内的令牌发送的消息会被客户端屏蔽。
